### ISSUE TITLE
Doesn't work - freeze at line 477 

### ISSUE THREAD

**Issue by crantisz** [Shriinivas/blenderbezierutils#4]
Here Keyboard Interrupt of endless cycle:

```
Traceback (most recent call last):
  File "/home/design/.config/blender/2.81/scripts/addons/blenderbezierutils.py", line 3089, in modal
    return self.subModal(context, event, snapProc)
  File "/home/design/.config/blender/2.81/scripts/addons/blenderbezierutils.py", line 5063, in subModal
    self.refreshDisplaySelCurves(displayInfosMap, locOnCurve)
  File "/home/design/.config/blender/2.81/scripts/addons/blenderbezierutils.py", line 4631, in refreshDisplaySelCurves
    ModalFlexiEditBezierOp.refreshDisplay(displayInfos, locOnCurve, self.snapper)
  File "/home/design/.config/blender/2.81/scripts/addons/blenderbezierutils.py", line 4611, in refreshDisplay
    ModalBaseFlexiOp.refreshDisplayBase(displayInfos, snapper)
  File "/home/design/.config/blender/2.81/scripts/addons/blenderbezierutils.py", line 2994, in refreshDisplayBase
    areaRegionInfo = getAllAreaRegions()
  File "/home/design/.config/blender/2.81/scripts/addons/blenderbezierutils.py", line 478, in getAllAreaRegions
    areas = [a for a in bpy.data.screens[i].areas if(a.type == 'VIEW_3D')]
  File "/home/design/.config/blender/2.81/scripts/addons/blenderbezierutils.py", line 478, in <listcomp>
    areas = [a for a in bpy.data.screens[i].areas if(a.type == 'VIEW_3D')]
KeyboardInterrupt

```

**Comment by Shriinivas** [comment]
This is fixed. Please check with the latest version.

**Comment by Shriinivas** [comment]
Closing this issue. You may reopen, if you face the problem again.

**Comment by crantisz** [comment]
Yes, last version works, thanks
